export const tokens = {
  colors: {
    primary: '#C8102E',
    primary_dark: '#A00D24',
    primary_light: '#FCE4EC',
    secondary: '#4A4A4A',
    secondary_light: '#F5F5F5',
    background: '#FFFFFF',
    surface: '#FAFAFA',
    text_primary: '#212121',
    text_secondary: '#757575',
    text_on_primary: '#FFFFFF',
    border: '#E0E0E0',
    success: '#4CAF50',
    warning: '#FFC107',
    danger: '#F44336',
    info: '#2196F3',
    semaphore_red: '#F44336',
    semaphore_yellow: '#FFC107',
    semaphore_green: '#4CAF50',
  },
  typography: {
    font_family: 'Inter, sans-serif',
    headings: {
      h1: {
        size: 32,
        weight: 700,
        line_height: 1.2,
      },
      h2: {
        size: 24,
        weight: 600,
        line_height: 1.3,
      },
      h3: {
        size: 20,
        weight: 600,
        line_height: 1.4,
      },
      h4: {
        size: 18,
        weight: 500,
        line_height: 1.4,
      },
    },
    body: {
      large: {
        size: 16,
        weight: 400,
        line_height: 1.5,
      },
      medium: {
        size: 14,
        weight: 400,
        line_height: 1.5,
      },
      small: {
        size: 12,
        weight: 400,
        line_height: 1.4,
      },
    },
    label: {
      size: 12,
      weight: 600,
      letter_spacing: 0.5,
      text_transform: 'uppercase',
    },
    caption: {
      size: 11,
      weight: 400,
      line_height: 1.3,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  border_radius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  shadows: {
    card: '0 2px 4px rgba(0,0,0,0.08)',
    elevated: '0 4px 12px rgba(0,0,0,0.12)',
    modal: '0 8px 24px rgba(0,0,0,0.16)',
  },
  iconography: {
    style: 'outline',
    size_sm: 16,
    size_md: 20,
    size_lg: 24,
  },
  motion: {
    duration_fast: 150,
    duration_normal: 300,
    easing: 'ease-in-out',
  },
};